import {NavItem} from './nav-item/nav-item';

// package icons

// https://wrappixel.github.io/premium-documentation-wp/angular/materialM/docs-icon.html

// https://icones.js.org/collection/solar?s=format
// https://tabler-icons.io/
// https://fontawesome.com/search?o=r



export const navItems: NavItem[] = [
  {
    navCap: 'Home',
  },
  {
    displayName: 'Dashboard',
    iconName: 'solar:atom-line-duotone',
    route: '/dashboard',
  },
  {
    displayName: 'Usuarios',
    iconName: 'solar:users-group-two-rounded-outline',
    route: '/gestion/usuarios',
    chipClass: 'bg-secondary text-white',
    chipContent: 'Nuevo',
  },
  {
    displayName: 'Eventos',
    iconName: 'solar:calendar-mark-outline',
    route: '/gestion/eventos',
    chipClass: 'bg-secondary text-white',
    chipContent: 'Nuevo',
  },
  {
    displayName: 'Formatos',
    iconName: 'solar:folder-favourite-bookmark-line-duotone',
    route: '/gestion/formatos',
    chipClass: 'bg-secondary text-white',
    chipContent: 'Nuevo',
  },
  {
    displayName: 'Firmas',
    iconName: 'solar:pen-new-square-outline',
    route: '/gestion/firmas',
    chipClass: 'bg-secondary text-white',
    chipContent: 'Nuevo',
  },
  {
    displayName: 'FlashCards',
    iconName: 'solar:bill-list-line-duotone',
    route: '/gestion/flashcards',
    chipClass: 'bg-secondary text-white',
    chipContent: 'Nuevo',
  },
  // {
  //   displayName: 'Analytics',
  //   iconName: 'solar:widget-add-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'eCommerce',
  //   iconName: 'solar:chart-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'CRM',
  //   iconName: 'solar:screencast-2-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  //
  // {
  //   divider: true,
  //   navCap: 'Apps',
  // },
  // {
  //   displayName: 'Chat',
  //   iconName: 'solar:chat-round-line-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Calendar',
  //   iconName: 'solar:calendar-mark-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Email',
  //   iconName: 'solar:letter-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Kanban',
  //   iconName: 'solar:clapperboard-edit-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Contacts',
  //   iconName: 'solar:phone-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'ContactsApp',
  //   iconName: 'solar:phone-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Courses',
  //   iconName: 'solar:book-bookmark-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Employee',
  //   iconName: 'solar:user-id-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Notes',
  //   iconName: 'solar:document-text-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Tickets',
  //   iconName: 'solar:ticket-sale-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'ToDo',
  //   iconName: 'solar:airbuds-case-minimalistic-line-duotone',
  //   route: '#',
  //   chip: true,
  //   external: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Invoice',
  //   iconName: 'solar:bill-list-line-duotone',
  //   route: '',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'List',
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       chip: true,
  //       external: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Detail',
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       chip: true,
  //       external: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Create',
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       chip: true,
  //       external: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Edit',
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       chip: true,
  //       external: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Blog',
  //   iconName: 'solar:widget-4-line-duotone',
  //   route: '#',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'Post',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       chip: true,
  //       external: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Detail',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       chip: true,
  //       external: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  //
  // {
  //   navCap: 'Ui Components',
  //   divider: true
  // },
  // {
  //   displayName: 'Badge',
  //   iconName: 'solar:archive-minimalistic-line-duotone',
  //   route: '/ui-components/badge',
  // },
  // {
  //   displayName: 'Chips',
  //   iconName: 'solar:danger-circle-line-duotone',
  //   route: '/ui-components/chips',
  // },
  // {
  //   displayName: 'Lists',
  //   iconName: 'solar:bookmark-square-minimalistic-line-duotone',
  //   route: '/ui-components/lists',
  // },
  // {
  //   displayName: 'Menu',
  //   iconName: 'solar:file-text-line-duotone',
  //   route: '/ui-components/menu',
  // },
  // {
  //   displayName: 'Tooltips',
  //   iconName: 'solar:text-field-focus-line-duotone',
  //   route: '/ui-components/tooltips',
  // },
  // {
  //   displayName: 'Forms',
  //   iconName: 'solar:file-text-line-duotone',
  //   route: '/ui-components/forms',
  // },
  // {
  //   displayName: 'Tables',
  //   iconName: 'solar:tablet-line-duotone',
  //   route: '/ui-components/tables',
  // },
  // {
  //   displayName: 'Expansion Panel',
  //   iconName: 'solar:inbox-archive-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Dialog',
  //   iconName: 'solar:bolt-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Divider',
  //   iconName: 'solar:menu-dots-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Paginator',
  //   iconName: 'solar:tuning-2-bold-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Nuevogress Bar',
  //   iconName: 'solar:restart-bold-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Nuevogress Spinner',
  //   iconName: 'solar:refresh-circle-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Ripples',
  //   iconName: 'solar:branching-paths-up-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Slide Toggle',
  //   iconName: 'solar:round-alt-arrow-right-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Slider',
  //   iconName: 'solar:tuning-3-bold-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Snackbar',
  //   iconName: 'solar:layers-minimalistic-bold-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Tabs',
  //   iconName: 'solar:box-minimalistic-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Toolbar',
  //   iconName: 'solar:balloon-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Tooltips',
  //   iconName: 'solar:feed-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  //
  // {
  //   divider: true,
  //   navCap: 'Pages',
  // },
  // {
  //   displayName: 'Roll Base Access',
  //   iconName: 'solar:lock-password-unlocked-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Treeview',
  //   iconName: 'solar:bill-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Pricing',
  //   iconName: 'solar:dollar-minimalistic-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Account Setting',
  //   iconName: 'solar:accessibility-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'FAQ',
  //   iconName: 'solar:question-square-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Landingpage',
  //   iconName: 'solar:layers-minimalistic-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Widgets',
  //   iconName: 'solar:widget-2-line-duotone',
  //   route: '#',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'Cards',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Banners',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Charts',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  //
  // {
  //   navCap: 'Extra',
  //   divider: true
  // },
  // {
  //   displayName: 'Icons',
  //   iconName: 'solar:sticker-smile-circle-2-line-duotone',
  //   route: '/extra/icons',
  // },
  // {
  //   displayName: 'Sample Page',
  //   iconName: 'solar:planet-3-line-duotone',
  //   route: '/extra/sample-page',
  // },
  //
  // {
  //   divider: true,
  //   navCap: 'Forms',
  // },
  // {
  //   displayName: 'Form elements',
  //   iconName: 'solar:password-minimalistic-input-line-duotone',
  //   route: '#',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'Autocomplete',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Button',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Checkbox',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Radio',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Datepicker',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Form Layouts',
  //   iconName: 'solar:file-text-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Form Horizontal',
  //   iconName: 'solar:align-horizonta-spacing-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Form Vertical',
  //   iconName: 'solar:align-vertical-spacing-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Form Wizard',
  //   iconName: 'solar:archive-minimalistic-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Toastr',
  //   iconName: 'solar:notification-lines-remove-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  //
  // {
  //   divider: true,
  //   navCap: 'Tables',
  // },
  // {
  //   displayName: 'Tables',
  //   iconName: 'solar:tablet-line-duotone',
  //   route: '#',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'Basic Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Dynamic Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Expand Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Filterable Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Footer Row Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'HTTP Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Mix Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Multi Header Footer',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Pagination Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Row Context Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Selection Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Sortable Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Sticky Column',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Sticky Header Footer',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Data table',
  //   iconName: 'solar:database-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  //
  // {
  //   divider: true,
  //   navCap: 'Chart',
  // },
  // {
  //   displayName: 'Line',
  //   iconName: 'solar:align-top-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Gredient',
  //   iconName: 'solar:bolt-circle-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Area',
  //   iconName: 'solar:chart-square-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Candlestick',
  //   iconName: 'solar:align-left-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Column',
  //   iconName: 'solar:chart-2-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Doughnut & Pie',
  //   iconName: 'solar:pie-chart-2-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Radialbar & Radar',
  //   iconName: 'solar:align-vertical-center-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  //
  // {
  //   divider: true,
  //   navCap: 'Auth',
  // },
  // {
  //   displayName: 'Login',
  //   iconName: 'solar:lock-keyhole-minimalistic-line-duotone',
  //   route: '/authentication',
  //   children: [
  //     {
  //       displayName: 'Login',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/authentication/login',
  //     },
  //     {
  //       displayName: 'Side Login',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Register',
  //   iconName: 'solar:user-plus-rounded-line-duotone',
  //   route: '/authentication',
  //   children: [
  //     {
  //       displayName: 'Register',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/authentication/register',
  //     },
  //     {
  //       displayName: 'Side Register',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Forgot Pwd',
  //   iconName: 'solar:password-outline',
  //   route: '/authentication',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'Side Forgot Pwd',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Boxed Forgot Pwd',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Two Steps',
  //   iconName: 'solar:siderbar-line-duotone',
  //   route: '/authentication',
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  //   children: [
  //     {
  //       displayName: 'Side Two Steps',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //     {
  //       displayName: 'Boxed Two Steps',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '#',
  //       external: true,
  //       chip: true,
  //       chipClass: 'bg-secondary text-white',
  //       chipContent: 'Nuevo',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Error',
  //   iconName: 'solar:bug-minimalistic-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },
  // {
  //   displayName: 'Maintenance',
  //   iconName: 'solar:settings-line-duotone',
  //   route: '#',
  //   external: true,
  //   chip: true,
  //   chipClass: 'bg-secondary text-white',
  //   chipContent: 'Nuevo',
  // },

];
